services:
  mongo: 
    image: mongo
    container_name: mongo-container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      
  backend:
    build:
      context: ./be
    container_name: backend-container
    ports:
      - 8080:8080
    environment:
      NODE_ENV: 'pro'
      PRO_MONGO_HOST: mongo
      PRO_MONGO_PORT: 27017
      PRO_MONGO_NAME: meca
      PRO_MONGO_USERNAME: root
      PRO_MONGO_PASSWORD: secret
      ADMIN_EMAIL_ADDRESS:
      GOOGLE_MAILER_CLIENT_ID:
      GOOGLE_MAILER_CLIENT_SECRET:
      GOOGLE_MAILER_REFRESH_TOKEN:
    depends_on:
      - mongo

  realtime:
    build: 
      context: ./realtime
    container_name: realtime-container
    ports:
      - 4000:4000
    environment:
      NODE_ENV: 'pro'
      PRO_MONGO_HOST: mongo
      PRO_MONGO_PORT: 27017
      PRO_MONGO_NAME: meca
      PRO_MONGO_USERNAME: root
      PRO_MONGO_PASSWORD: secret
    depends_on:
      - mongo
  
  frontend:
    build:
      context: ./fe
    container_name: frontend-container
    ports:
      - 80:80
    depends_on:
      - backend
      - realtime
volumes:
  database:
    name: meca-mongo

